apiVersion: batch/v1
kind: Job
metadata:
  name: 1workgroup
  labels:
    app: 1workgroup
spec:
  completions: 4
  parallelism: 4
  manualSelector: true
  selector:
    matchLabels:
      app: 1workgroup
  template:
    metadata:
      labels:
        app: 1workgroup
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: 1workgroup
          image: artifactory.cooppank.eu/docker-snapshot/nworkgroup:0.1.0
          # command:
          #   - "sh"
          #   - "-c"
          #   - "tail -f /dev/null"
          env:
            - name: APIURL
              value: "http://usersgen:8080"
            - name: USERCOUNT
              value: "2500"
            - name: WORKERCOUNT
              value: "3"
            - name: CARDWORKERCOUNT
              value: "6"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
